(*
	Purpose:
		This is used for creating menus for AppleScript apps that stay in the
		menu bar. It makes simpler to create a menu using Foundation on the main
		app script.

	@Project:
		applescript-core

	@Build:
		./scripts/build-lib.sh core/Level_2/menu

	@Example:
		Check if menu is checked
			menu item "Minimap" of menu 1 of menu item "Appearance" of menu 1 of menu bar item "View" of menu bar 1
			return value of attribute "AXMenuItemMarkChar" of result is equal to unic's MENU_CHECK

	@Testing:
		Test with Menu Pinned.  Cannot test the UI functionality because menu apps need to be deployed.

	@Created: Saturday, September 30, 2023 at 5:50:31 PM
	@Last Modified: 2026-08-25 14:10:00
	
	@Change Logs:
		Tue, Sep 15, 2026 - addMenuItem optional lookupKey sets representedObject for URL map keys.
		Fri, Sep 04, 2026, at 12:11:52 PM - Additional handlers, generated by AI.
*)
use scripting additions

use framework "Foundation"
use framework "AppKit"

use loggerFactory : script "core/logger-factory"

property logger : missing value

property isSpot : false

if {"Script Editor", "Script Debugger", "osascript"} contains the name of current application then spotCheck()

on spotCheck()
	loggerFactory's inject(me)
	logger's start()
	
	logger's finish()
end spotCheck


(*  *)
on new(pMenuAppObject, menuBarTitle)
	loggerFactory's inject(me)
	
	if isSpot is false then
		set bar to current application's NSStatusBar's systemStatusBar
		set localStatusItem to bar's statusItemWithLength:-1.0
		
		localStatusItem's setTitle:menuBarTitle
		
		set newMenu to current application's NSMenu's alloc()'s initWithTitle:menuBarTitle
		newMenu's setDelegate:pMenuAppObject
		localStatusItem's setMenu:newMenu
	else
		set newMenu to missing value
	end if
	
	script MenuUtilInstance
		property menuAppObject : pMenuAppObject
		property menuElement : newMenu
		property statusItem : localStatusItem
		
		on addSeparator()
			if isSpot then return missing value
			
			set sepMenuItem to (current application's NSMenuItem's separatorItem())
			(menuElement's addItem:sepMenuItem)
		end addSeparator
		
		
		(*
			Non-interactive section header (no action, no target).
		*)
		on createSectionTitle(title)
			if isSpot then return missing value
			
			set noAction to missing value
			(* 
			set sectionMenuItem to (current application's NSMenuItem's alloc()'s initWithTitle:title action:noAction keyEquivalent:"")
			(menuElement's addItem:sectionMenuItem)
			*)
			set sectionMenuItem to (current application's NSMenuItem's sectionHeaderWithTitle:title)
			(menuElement's addItem:sectionMenuItem)
			
			(sectionMenuItem's setEnabled:false)
			
			set boldFont to current application's NSFont's boldSystemFontOfSize:12
			set labelColor to current application's NSColor's secondaryLabelColor
			set attrs to current application's NSDictionary's dictionaryWithObjects:{boldFont, labelColor} forKeys:{current application's NSFontAttributeName, current application's NSForegroundColorAttributeName}
			set attrTitle to (current application's NSAttributedString's alloc()'s initWithString:title attributes:attrs)
			sectionMenuItem's setAttributedTitle:attrTitle
			
			sectionMenuItem
		end createSectionTitle
		
		
		on clearMenuItems()
			clear()
		end clearMenuItems
		
		
		on clear()
			if isSpot then return
			
			-- menuElement's removeAllItems()
			
			repeat while (menuElement's numberOfItems() > 0)
				menuElement's removeItemAtIndex:0
			end repeat
		end clear
		
		
		(*  tea-such
			@action - e.g. "menuAction:"
			@useCommand - Use the "Command key" for the shortcut key.
		*)
		on createRootMenuItem(title, action, enabledState, shortcutKey, useCommand, checkedState)
			if isSpot then return missing value
			
			-- Auto-correction.
			if action is not missing value and action does not end with ":" then set action to action & ":"
			
			set newMenuItem to (current application's NSMenuItem's alloc()'s initWithTitle:title action:action keyEquivalent:shortcutKey)
			if useCommand then newMenuItem's setKeyEquivalentModifierMask:(current application's NSEventModifierFlagCommand)
			(menuElement's addItem:newMenuItem)
			(newMenuItem's setEnabled:enabledState)
			(newMenuItem's setState:checkedState)
			if enabledState then (newMenuItem's setTarget:menuAppObject)
			
			newMenuItem
		end createRootMenuItem
		
		
		(*
			@action - e.g. "menuAltAction:"
		*)
		on createOptionalRootMenuItem(title, action, checkedState)
			if isSpot then return missing value
			
			-- Auto-correction.
			if action is not missing value and action does not end with ":" then set action to action & ":"
			
			set altMenuItem to (current application's NSMenuItem's alloc()'s initWithTitle:title action:action keyEquivalent:"")
			set altMenuItem's alternate to true
			(altMenuItem's setKeyEquivalentModifierMask:(current application's NSEventModifierFlagOption))
			(menuElement's addItem:altMenuItem)
			(altMenuItem's setState:checkedState)
			(altMenuItem's setTarget:menuAppObject)
			
			altMenuItem
		end createOptionalRootMenuItem
		
		
		(*
			@action - e.g. "menuAltAction:"
		*)
		on createOptionalRootMenuItemWithCommand(title, action, shortcutKey, checkedState)
			if isSpot then return missing value
			
			-- Auto-correction.
			if action is not missing value and action does not end with ":" then set action to action & ":"
			
			set altMenuItem to (current application's NSMenuItem's alloc()'s initWithTitle:title action:action keyEquivalent:shortcutKey)
			set altMenuItem's alternate to true
			set modifierMask to (current application's NSEventModifierFlagCommand)
			altMenuItem's setKeyEquivalentModifierMask:(modifierMask + (current application's NSEventModifierFlagOption))
			(menuElement's addItem:altMenuItem)
			(altMenuItem's setState:checkedState)
			(altMenuItem's setTarget:menuAppObject)
			
			altMenuItem
		end createOptionalRootMenuItemWithCommand
		
		
		on createSubMenu(title, sourceMenuItems, action, selectedItem, submenuItemHandler)
			if isSpot then return
			
			set newSubMenu to (current application's NSMenu's alloc()'s initWithTitle:("title-unused"))
			repeat with nextSourceMenuItem in sourceMenuItems
				-- logger's debugf("nextSourceMenuItem: {}", nextSourceMenuItem)
				set nextProcessedMenuItemTitle to nextSourceMenuItem
				try
					if submenuItemHandler is not missing value then
						set nextProcessedMenuItemTitle to submenuItemHandler's handleNextElement(nextSourceMenuItem)
					end if
				end try
				
				set nextSubMenuItem to (current application's NSMenuItem's alloc()'s initWithTitle:nextProcessedMenuItemTitle action:action keyEquivalent:"")
				(newSubMenu's addItem:nextSubMenuItem)
				set nextItemChecked to selectedItem is equal to nextSourceMenuItem as text
				(nextSubMenuItem's setState:(nextItemChecked))
				(nextSubMenuItem's setTarget:menuAppObject)
			end repeat
			
			-- Add the sub-menu to the main menu
			set subMenuTitle to (current application's NSString's stringWithString:title)
			set subMenuItem to (current application's NSMenuItem's alloc()'s initWithTitle:subMenuTitle action:action keyEquivalent:"")
			(subMenuItem's setSubmenu:newSubMenu)
			(menuElement's addItem:subMenuItem)
			(subMenuItem's setEnabled:true)
			(subMenuItem's setTarget:menuAppObject) -- required for enabling the menu item
		end createSubMenu
		
		
		(*
			Adds a clickable item to targetMenu, or to the status bar root menu when targetMenu is missing value.
			@action - e.g. "directMenuAction:"
			@lookupKey - optional; stored as representedObject when not missing value (e.g. composite directUrls key).
		*)
		on addMenuItem(targetMenu, title, action, checkedState, lookupKey)
			if isSpot then return missing value
			
			if targetMenu is missing value then set targetMenu to menuElement
			
			if action is not missing value and action does not end with ":" then set action to action & ":"
			
			set newMenuItem to (current application's NSMenuItem's alloc()'s initWithTitle:title action:action keyEquivalent:"")
			(targetMenu's addItem:newMenuItem)
			(newMenuItem's setEnabled:true)
			(newMenuItem's setState:checkedState)
			if action is not missing value then (newMenuItem's setTarget:menuAppObject)
			if lookupKey is not missing value then (newMenuItem's setRepresentedObject:(current application's NSString's stringWithString:(lookupKey as text)))
			
			newMenuItem
		end addMenuItem
		
		
		(*
			Attaches an empty submenu titled title on targetMenu (root when missing value).
			@returns the NSMenu to fill with addMenuItem/addSubMenu.
		*)
		on addSubMenu(targetMenu, title)
			if isSpot then return missing value
			
			if targetMenu is missing value then set targetMenu to menuElement
			
			set newSubMenu to (current application's NSMenu's alloc()'s initWithTitle:("title-unused"))
			set noAction to missing value
			set subMenuItem to (current application's NSMenuItem's alloc()'s initWithTitle:title action:noAction keyEquivalent:"")
			(subMenuItem's setSubmenu:newSubMenu)
			(targetMenu's addItem:subMenuItem)
			(subMenuItem's setEnabled:true)
			(subMenuItem's setTarget:menuAppObject)
			
			newSubMenu
		end addSubMenu
		
		
		on setTitle(newTitle)
			if isSpot then return
			
			statusItem's setTitle:(newTitle)
		end setTitle
	end script
end new

